### ISSUE TITLE
Could I port this to the haxe vscode externs?

### ISSUE THREAD

**Issue by Jarrio** [Kode/vscode-kha#1]
I've been meaning to make a vscode kha extension but don't really have experience in nodejs. 

What's your opinion on just using the haxe [vscode](https://github.com/vshaxe/vscode-extern) externs instead so we can use haxe to develop the extension?

**Comment by Jarrio** [comment]
@RobDangerous

**Comment by RobDangerous** [comment]
Depends, no idea what you plan to do. With the current scope of this extension (figuring out some paths and calling khamake basically) it would IMHO be silly to use anything else but the native vscode extension language (aka JavaScript).

**Comment by Jarrio** [comment]
I've got a basic setup in my current haxe extension where I just ask the user to set the path of their kha installation and set the path in the `settings.json` file

**Comment by RobDangerous** [comment]
And plans beyond that? I like pull requests but, rough estimate, as long as the source code of the extension stays way below the size of the externs I don't feel good about adding externs. Feels so Bloaty McBloatface. Can we agree on switching to Haxe once it starts making sense?

**Comment by Gama11** [comment]
>as long as the source code of the extension stays way below the size of the externs I don't feel good about adding externs

Random thought: there can hardly be any VSCode extensions meeting that bar, according to this the VSCode API has 184 unique types these days. ;)

![](https://i.imgur.com/UFbA1sb.png)

This is also about attracting more potential contributors. This is a VSCode extension for a _Haxe Framework_ after all, I don't think many Haxe developers are interested in writing JS code (me included).

_______________

I would like to see the Kha extension have a similar feature set as the [Lime extension](https://github.com/openfl/lime-vscode-extension), meaning:

- status bar items to switch between targets + debug/release
- a task provider that generates tasks for the currently selected config (target + debug/release)
- integration with VSHaxe's completion provider API

Maybe @Jarrio is interested in looking into that? I don't have time for it myself at the moment unfortunately (and am not a Kha user to begin with), but I'd still like to see these things happen.

**Comment by Jarrio** [comment]
There are other things we can add as well:

- Task switcher like the lime extension provides
  - Task provider
- Use vshaxe's extension API

Kha's build process also doesn't expose `--connect` currently but we can use the api to gain access to the compiler cache rather than the current method which is to manually fill the port in and add it as a `addParameter` in khafile.js. A temporary solution could be to just add a filewatcher to the `.hxml` files and append it on change.

I think in terms of file size it would never make sense to use an extern. But it doesn't seem like a bad idea to keep a Haxe extension within the Haxe ecosystem

**Comment by RobDangerous** [comment]
| Language        |             files    |      blank    |    comment     |      code
| ----------------|----------------|-------------|-----------------|-----------------
| Haxe                |           188      |      824       |    5133      |     1584
| SUM:                |           188      |      824      |     5133      |     1584

It's a good deal and I'll go with it. We cross 1584 lines of code I'll switch it to Haxe.

**Comment by Gama11** [comment]
>We cross 1584 lines of code I'll switch it to Haxe.

I think that can be summarized as a "no" then, considering the Lime extension currently only has around half that (with empty lines), and it uses that ridiculous OpenFL code style (with many empty lines). Fair enough, I have enough other projects to contribute to.

**Comment by RobDangerous** [comment]
Oh, I thought that would be more. So, yes, if we are talking about a < 1000 lines end goal here I indeed prefer simplicity to more pull requests. Sorry.

**Comment by Jarrio** [comment]
No worries, just figured it was a way I could contribute 👍

**Comment by sh-dave** [comment]
Somehow i totally missed this. I don't care about the plugin being in haxe all that much, but about a point raised by @Gama11.

- status bar items to switch between targets + debug/release
- a task provider that generates tasks for the currently selected config (target + debug/release)

Currently i use vscode's `configure default build task` (that generates an entry in task.json) so i don't have to select the target everytime i hit `ctrl + shift + b`. Having that as an option in the status bar (instead of the current `completion provider`) would be helpful. At the moment when i want to switch the target, i have to `configure default build task` again, and select a different `completion provider` in the status bar.

**Comment by nadako** [comment]
Meh, I wanted to look into adding support for compiler cache server for faster builds, but found out the extension is pure-JS which I can't be arsed to work with :(

**Comment by RobDangerous** [comment]
Sorry but I don't like using Haxe for something that's only ever compiled to JS.

**Comment by Gama11** [comment]
>it would IMHO be silly to use anything else but the **native vscode extension language** (aka JavaScript).

FWIW, that's arguably TypeScript, not JavaScript. ;)

**Comment by RobDangerous** [comment]
I use that for vscode extensions which are not super small.
