### ISSUE TITLE
[BUG?] can not quit running debug application with keystroke

### ISSUE THREAD

**Issue by lewislepton** [Kode/vscode-kha#13]
as the title says. the running debug html window does not close when using the keystroke of `cmd-q`, not sure how windows users fair off

**Comment by RobDangerous** [comment]
It's a Mac only issue, everywhere else Electron treats closing the last Window and closing the application as the same thing.

**Comment by lewislepton** [comment]
not sure if you've spotted other bugs with this. but ive just noticed that also the nice way to rerun the same running debug application with `cmd-r` [since debug running is set to that for me] is also not working

**Comment by RblSb** [comment]
This can be configured with `Keyboard.disableSystemInterventions(None);` or with custom function, see https://github.com/Kode/Kha/blob/master/Sources/kha/input/Keyboard.hx#L6

**Comment by lewislepton** [comment]
yo @RobDangerous - just wondering if this could be looked at?

thanks
x

**Comment by RobDangerous** [comment]
Hm, I guess I'll just put in what RblSb told us to put in.

**Comment by RobDangerous** [comment]
Fixed in latest Kha.
