### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by matrefeytontias** [Kode/vscode-kha#21]
- Issue Type: `Performance`
- Extension Name: `kha`
- Extension Version: `20.1.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.41.1`

CPU profile : [kodetech.kha-unresponsive.cpuprofile.txt](https://github.com/Kode/vscode-kha/files/4036352/kodetech.kha-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

---
The Kha extension is reported by VS Code as "taking a very long time" and preventing other extensions from working correctly. As you can see from the CPU profile, the extension is stuck in addLibrary, in `Kha/Tools/khamake/out/Project.js`. Additionally, pressing Ctrl+Shift+B to display build tasks never completes, making the "Fetching build tasks..." message stay indefinitely in the bottom left of the window.

**Comment by matrefeytontias** [comment]
Update : `addLibrary` seems to be broken by the `dependencies` field of libraries' haxelib.json files.

**Comment by RobDangerous** [comment]
The fetching build tasks-problem is solved, don't know whether that also solved the high cpu load message. Also don't know what your latest comment even means.

**Comment by matrefeytontias** [comment]
Try using [HaxePunk](https://github.com/HaxePunk/HaxePunk/) through `addLibrary('HaxePunk')` after replacing `"install"` by `"dependencies"` on line 10 of [the library's `haxelib.json`](https://github.com/HaxePunk/HaxePunk/blob/dev/haxelib.json). As far as I know, `install` is legacy and `dependencies` is the currently valid keyword.

**Comment by RobDangerous** [comment]
But that's not at all related to the vscode extension, right?

**Comment by matrefeytontias** [comment]
Well it is, because using "dependencies" instead of "install" is what causes the infinite "fetching build tasks" and the "Kha took a very long time" error message for me.

**Comment by RobDangerous** [comment]
Well, that's a side-effect then. I'll close this one, open a khamake issue about it please.
