### ISSUE TITLE
Can't initialize a new project in the extension

### ISSUE THREAD

**Issue by pyrofolium** [Kode/vscode-kha#23]
I'm on a mac with a fresh install of kha extension on mac osx. 

I've pointed the kha path to an external one:  /usr/local/lib/haxelib/kha

<img width="446" alt="Settings_—_haxe_learn" src="https://user-images.githubusercontent.com/1806857/85951830-9d71f180-b91a-11ea-83d9-e049fbf391a5.png">

**Comment by RobDangerous** [comment]
Sorry, overlooked this. What does git status output in  /usr/local/lib/haxelib/kha?

**Comment by RobDangerous** [comment]
Hm, no feedback :(
