### ISSUE TITLE
vs ignores libraries.

### ISSUE THREAD

**Issue by lublak** [Kode/vscode-kha#31]
I have a khafile.js

```js
let project = new Project('New Project');
project.addAssets('Assets/**');
project.addShaders('Shaders/**');
project.addSources('Sources');
project.addLibrary('ldtk-haxe-api');
resolve(project);
```

but vscode ignores that i added ldtk-haxe-api:

![grafik](https://user-images.githubusercontent.com/44057030/128851717-b3f21409-1cd6-4d3c-a684-022e0860a709.png)

but it builds without errors.

![grafik](https://user-images.githubusercontent.com/44057030/128851876-5c3c0f3c-dffa-4441-a442-00ff6784ca45.png)

**Comment by sh-dave** [comment]
It should work if you reload vscode or restart the haxe language server.

**Comment by lublak** [comment]
I tried "restart the haxe language server" and restarting vscode. After restarting my complete pc it works. @sh-dave 
Sometimes its a bit buggy with vscode and kha.

**Comment by sh-dave** [comment]
I'm not sure, but I think it's more vscode + haxe, as i have these problems with non-kha projects as well.
