### ISSUE TITLE
Error while performing the task

### ISSUE THREAD

**Issue by e1e5en-gd** [Kode/vscode-kha#41]
1. Downloaded VSCode.
2. Installed the extension.
3. Installed Node.js v18.16.0.
4. Opened the folder in the editor.
5. Created a project.
6. When I try to start, I get a message:

![image](https://github.com/Kode/vscode-kha/assets/7114353/4744220c-f103-4ef6-8d66-38c89a9d15e2)

When you click on `Debug Anyway`, I get the message:

![image](https://github.com/Kode/vscode-kha/assets/7114353/0167e2a8-9fa2-40e7-aaa7-14fadd76ffda)

In the editor 's terminal , the following messages are displayed:
![image](https://github.com/Kode/vscode-kha/assets/7114353/d943ae10-824b-4642-bb38-355913452ceb)

**Comment by e1e5en-gd** [comment]
Visual Studio Code has been updated. Rearranged the plugin and recreated the project. The message about the absence of Electron has disappeared. Now it displays a message from the terminal returning exit code 1 and a message in the terminal that the module was not found. The application starts, there is a window, but when you try to change the code, nothing changes.

![image](https://github.com/Kode/vscode-kha/assets/7114353/5a2abcea-f85c-444b-8383-8276d550aae6)

**Comment by RobDangerous** [comment]
What does "Rearranged the plugin" mean? What is the "message from the terminal" and what is the "message in the terminal that the module was not found"? The same as before?

**Comment by e1e5en-gd** [comment]
After updating the editor, I removed and reinstalled the plugin. 
As a result, only one message ("Error launching app") was missing. Otherwise, the output has not changed, just as I indicated in the first comment.

**Comment by RobDangerous** [comment]
ok, so the interesting thing seems to be the "Cannot find module 'bla bla bla kha-23.4.0Khamake.js'" but I have no idea how that can happen and failed to reproduce it even with installing the same version of node and a fresh installation of the extension with no options set. Do you also get the error when you run "node c:\Users\e1e5e\.vscode\extensions\kodetech.kha-23.4.0\Kha\make.js debug-html5 --debug" outside of vscode?

**Comment by e1e5en-gd** [comment]
Everything works. At least the command is executed.
![image](https://github.com/Kode/vscode-kha/assets/7114353/25fdc3bb-1609-4d4a-8b9c-b506cdb8ff89)

**Comment by RobDangerous** [comment]
Strange. I have no idea why running it in vscode is different.

**Comment by e1e5en-gd** [comment]
This is on any project. Here I created a new one, and the same problem. Something is breaking the path to the file. At least, what is displayed here is completely wrong (the paths are mixed and the separators disappear somewhere). Maybe it's just a conclusion like this:

`Error: Cannot find module 'c:\GDev\Project_Kha\t7\Userse1e5e.vscodeextensionskodetech.kha-23.4.0Khamake.js'`

**Comment by RobDangerous** [comment]
Yes, I saw that. But no idea how it happens. And why it only happens in vscode and only for you.

**Comment by RblSb** [comment]
What terminal type is selected in vscode? Powershell or something else? There is some hacks about such things in extension code

**Comment by e1e5en-gd** [comment]
![image](https://github.com/Kode/vscode-kha/assets/7114353/f364bf6a-4be6-47f4-8a6a-ac01d4ccef4d)

If you change `Terminal: Select Default Profile` to `PowerShell` or `Command`, then everything works. I had `Git Bash`. Thank you. =)

**Comment by RobDangerous** [comment]
Hu, thanks RblSb, that was a mystery to me. That way I should also be able to repro it so I'll keep this issue open and see if I can fix it properly.

**Comment by RblSb** [comment]
Np, just remembered about related PR from my friend https://github.com/Kode/vscode-kha/pull/20

**Comment by RobDangerous** [comment]
Didn't remember, am too old.
